name: Java CI

on:
  push:
    branches: [ main ]
  


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java source
        run: |
          mkdir -p out
          javac -d out Main.java

      - name: Run application
        run: |
          java -cp out Main
      - name: Run custom Action
        id: java-action
        uses: ./actions/java-build
        with:
          src: Main.java
          main-class: Main

      - name: Show action output
        run: echo "Program output: ${{ steps.java-action.outputs.run-output }}"
        

